### ISSUE TITLE
'includeIn' can no longer be set as an attribute property

### ISSUE THREAD

**Issue by dougestey** [mdconaway/sails-ember-rest#6]
Hey friend, thanks for the fantastic work here. I just used this in a project and am extremely happy with it. Ember is awesome, Sails is awesome, and you're awesome.

I came across a sad today, and I'm not sure the issue belongs in your repo, so feel free to redirect me to knock on someone else's door. But either way, I thought you might want to know that it seems like Waterline (Sails 1.0.0-41) is now ignoring the following:

```javascript
validations: {
  ignoreProperties: ['includeIn']
}
```

...in sails.config.models. This makes configuring the presentation options impossible on a per-model basis with the latest version of sails-ember-rest.

```
error: The attribute `guests` on the `event` model contains invalid properties. The property `includeIn` isn't a recognized property.

error: Could not load Sails app.
```

I've been sleuthing around in Waterline trying to find something, anything, about specifying one's own reserved properties, but to no avail. I can't even find a doc about this breaking change. They appear to be defined here: https://github.com/balderdashy/waterline-schema/blob/master/accessible/valid-attribute-properties.js and enforced here: https://github.com/balderdashy/waterline-schema/blob/master/lib/waterline-schema/schema.js#L237

Anyway, thanks so much for this awesome repo. Let me know if there's any way I can help with this.

**Comment by mdconaway** [comment]
This is an important issue, thanks for bringing it up! I'll spend some time this weekend investigating if there is some other way to achieve this functionality in sails 1.0.x.

If you have any ideas on how to refactor this functionality let me know as I don't currently have a solid way forward on this one!

**Comment by mdconaway** [comment]
Hey @dougestey,

I think I may have found a workaround for this.

Check out this commit: https://github.com/mdconaway/sails-ember-rest/commit/23d18cbd25b6be1822207417f82be68ac845d0c9

I think we can use the "meta" key on an attribute to specify options specific to this library.  This will also remove the need to add the validation ignore configuration option to the global model config.

Let me know what you think about the solution outlined in the commit.  If you think it looks good and don't see any potential conflicts with using the attribute meta key I will modify the README and push the latest changes to NPM.

**Comment by dougestey** [comment]
@mdconaway great find! I was curious about that key myself. The only thing I might suggest is protecting against a potential conflict with anyone else using the meta key... maybe a prefix? It seems unlikely, but I have no idea how this key is used or by whom.

This seems like the way to go though, well done!

**Comment by mdconaway** [comment]
This feature is now listed in the README and is deployed on NPM with sails-ember-rest@1.0.13

**Comment by dougestey** [comment]
@mdconaway 🙏 really great work.
