### ISSUE TITLE
Support for multiple-word model names?

### ISSUE THREAD

**Issue by rjoxford** [mdconaway/sails-ember-rest#7]
I have installed this module, and its been working fine until I got to the model that had a multi-word name. For these multi-word names:

- I'm able to delete, and able to create a record, but with no attributes or relationships

- I'm unable to POST with attributes or PATCH/PUT any attributes

Are multiple word names supported / can they easily be? Thanks

**Comment by mdconaway** [comment]
Thanks for opening this issue!

Multi-word model names are supposed to be supported... if they are not then I must have broken something with converting model names between camel case and kebab case somewhere.

Should be an easy fix!  I'll write up some integration tests tonight and hopefully have a patch out for this issue by tomorrow.

Just for reference on this issue, can you please inspect the network traffic sent by your Ember RESTAdapter and give me some examples of the multi-word model names in the payload envelope?  I will use your specific model names for the integration tests I write.

**Comment by rjoxford** [comment]
Great, thanks for getting back so quickly. 

I'm afraid I've changed things slightly, but roughly like this. 

So I had an Ember model at 'assessment-question.js', corresponding to Sails model at 'AssessmentQuestion.js'.

Ember was sending requests such as a POST to localhost:4200/assessment-questions:

`{"assessmentQuestion":{"questionNumber":"1","question":"Testing","marks":3,"assessment":"2"}}`

This would be sufficient for Sails to create a new record, but not to populate it, with a response such as:
```
{
  "assessmentquestion": [
    {
      "createdAt": 1523556332356,
      "updatedAt": 1523556332356,
      "id": 2,
      "questionNumber": "",
      "question": "",
      "marks":0
    }
  ]
}
```
(not entirely sure how "assessmentquestion" in the root of this response was)

I might need to try and recreate if you need more details. Otherwise, I'll just thank you very much.

Not the right place to be asking, but would you be looking to move towards JSONAPI in future? Thanks again.

**Comment by mdconaway** [comment]
I just pushed 1.0.14, can you confirm that it meets the requirements for this issue request? If its all good I will close this issue.

**Comment by rjoxford** [comment]
Only tried it with Postman, but seems to have done the trick! I'm impressed with the quick turnaround - Thanks!

**Comment by mdconaway** [comment]
In reference to your JSONAPI question, I believe there have been at least three attempts at this:
https://github.com/sane/sails-hook-jsonapi
https://www.npmjs.com/package/sails-json-api-blueprints
https://www.npmjs.com/package/sails-generate-jsonapi-blueprints

But none of them appears to offer 100% of the capabilities outlined by JSONAPI.

I would be open to collaboratively working on a new project to accomplish JSONAPI in Sails, but I doubt this specific project will ever go that direction.  If anything, this project could serve as a good starting point for a JSONAPI fork though!

Let me know if you are interested in contributing to such a venture (it would probably best be accomplished with a group), but at the moment the REST Adapter fits 99% of my usage needs.

@sgress454
@mikermcneil
@sailshq

**Comment by rjoxford** [comment]
Hey, sorry for the slow reply. 

Same here - with this working nicely I'm free to actually concentrate on my ember app. So my thanks again for your hard work.

 Should the need arise, I'd certainly be glad to help as I could. Give me a shout.
